### ISSUE TITLE
您好！

### ISSUE THREAD

**Issue by zhenyan-chang** [liuf1986/LFRtmp#2]
加入我自己的推流地址，一直连接不上，我们不需要port，怎么处理

**Comment by liuf1986** [comment]
1935是rtmp服务的默认端口，就像80是http的默认端口一样，不显示的加端口就意味使用的是默认的1935端口。能否追踪一下代码看是否是sokcet连接的问题，或者将控制台的操作日志贴出来

**Comment by zhenyan-chang** [comment]
2016-09-01 10:53:14.311 LFRtmp[4924:927540] --------------RTMP：获取socket地址失败！--------------
2016-09-01 10:53:14.311 LFRtmp[4924:927540] --------------RTMP：创建socket通道失败！--------------

 [rtmpService start:@"rtmp://v.jstyle.cn/live/0825" port:1935];
这个推流地址，，，  能加个QQ:934356684  吗？
我稍微打扰您一下。谢谢了。

**Comment by zhenyan-chang** [comment]
握手成功，但是提示：连接失败，重连中······
大神是哪里出错了啊。
[rtmpService start:@"rtmp://v.jstyle.cn/live/0825" port:1935];
这个推流地址，，， 能加个QQ:934356684 吗？
我稍微打扰您一下。谢谢了。

**Comment by zhenyan-chang** [comment]
大神，麻烦帮助一下！

**Comment by liuf1986** [comment]
已更新rtmp包读取方式
